# upstream node_red {
#     server node-red:1880;
# }

server {
    listen      80;
    listen [::]:80;
    server_name localhost;

    # Enable CORS
    add_header 'Access-Control-Allow-Origin' '*';
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
    add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With';
    add_header 'Access-Control-Expose-Headers' 'Authorization';
    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Content-Security-Policy "default-src 'self'";


    # Path without authentication: /orion/version
    location /orion/version {
        proxy_pass http://orion:1026/version;
    }

    # Path without authentication: /orion/ngsi-ld/ex/v1/version
    location /orion/ngsi-ld/ex/v1/version {
        proxy_pass http://orion:1026/ngsi-ld/ex/v1/version;
    }

    # Proxy Orion protected with Keycloak authentication
    location /orion/ {
        proxy_pass http://orion:1026/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # JWT token verification with Keycloak
        auth_request /auth;
    }

    # Endpoint for token verification with Keycloak
    location = /auth {
        internal;
        proxy_pass http://keycloak:8080/realms/dedalus/protocol/openid-connect/userinfo;
        proxy_set_header Authorization $http_authorization;
    }

    # Proxy Node-RED
    location ~* /(editor|ui|worldmap) {
        proxy_pass http://node-red:1880;

        # Enable WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        # Disable buffer
        proxy_buffering off;
    }

    # Proxy Keycloak
    location /keycloakadmin {
        proxy_pass http://keycloak:8080;
        proxy_set_header Host $host;
	proxy_set_header X-Real_IP $remote_addr;
    }

    # Proxy Mongo-Express
    location /mongoadmin {
        proxy_pass http://fe-mongo:8081;
        proxy_set_header Host $host;
	proxy_set_header X-Real_IP $remote_addr;
    }

    location ^~ /smartdatamodels/ {
        proxy_pass https://smartdatamodels.org:1026/;
    }

    # Blockchain
    # location ^~ /ganache/ {
    #     proxy_http_version 1.1;
    #     proxy_set_header Upgrade $http_upgrade;
    #     proxy_set_header Connection "upgrade";
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header Host $http_host;
    #     proxy_set_header X-NginX-Proxy true;
    #     proxy_pass http://ganache:7545/;
    # }

    # Nginx web server
    location / {
        root /home/www/public_html/localhost/public;
        index index.html index.htm;
        try_files $uri $uri/ index.html =404;
        autoindex on;
    }

    error_page 401 = @error401;
    location @error401 {
        return 401 '"Unauthorized"';
        add_header Content-Type application/json;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
